# Site  
name: "Treasure Trove Bay"
title: "тов Treasure Trove Bay"
description: "Lifestyle, Travel, Products and Reviews"
logo: 'assets/images/logo.png'
favicon: 'treasure_trove_bay/assets/images/logo.png'
baseurl: /
google_analytics: 'G-J6Y66TDQZ7'
disqus: '' 
mailchimp-list: '1fe4646bdf'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jack:
    name: Jack Hunter
    display_name: Jack Hunter
    avatar: 'assets/images/CPT_Jack_Hunter.png'
    email: hunter@treasuretrovebay.com
    web: https://treasuretrovebay.com
    twitter: https://twitter.com/CptJackHunter
    facebook: https://www.facebook.com/145407415319886
    instagram: https://instagram.com/cpt.jackhunter
    description: "Head of TTB Information, Seeker of Knowledge, Wealth of Experince."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-5277841902191328"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
